[build]
  # Define what packages should be installed for the build
  [build.packages]
  dependencies = ["python", "pip", "uvicorn", "fastapi"]

[deploy]
  # Target environment
  target = "production"
